(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"1903281741200",f:(function(AMP,_){
var m,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={a:!0},ea={};try{ea.__proto__=da;ca=ea.a;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ga(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.za=b.prototype}var ha=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a}(this);function ia(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ja=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ka(a){var b=Object.create(null);if(!a)return b;for(var c;c=ja.exec(a);){var d=ia(c[1],c[1]),e=c[2]?ia(c[2],c[2]):"";b[d]=e}return b};var la="";
function q(){var a,b=a||self;if(b.AMP_MODE)var c=b.AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=ka(c.location.originalHash||c.location.hash);d=d.spt;var g=ka(c.location.search);la||(la=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011903281741200");c=b.AMP_MODE={localDev:!1,development:!("1"!=f.development&&!c.AMP_DEV_MODE),examiner:"2"==f.development,filter:f.filter,geoOverride:f["amp-geo"],minified:!0,lite:void 0!=g.amp_lite,test:e,log:f.log,version:"1903281741200",rtvVersion:la,
singlePassType:d}}return c};var ma=Object.prototype.toString;function r(a){return a?Array.prototype.slice.call(a):[]}function na(a){return"[object Object]"===ma.call(a)};function oa(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}self.log=self.log||{user:null,dev:null,userForEmbed:null};var u=self.log;function v(){if(!u.user)throw Error("failed to call initLogConstructor");return u.user}function w(){if(u.dev)return u.dev;throw Error("failed to call initLogConstructor");}
function x(a,b,c,d,e){return v().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var pa=Object.prototype.hasOwnProperty;function z(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function A(a){return a||{}}function B(a,b){if(pa.call(a,b))return a[b]}
function qa(a,b){var c=10;c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.t=b.t;a.s=b.s;a.d=b.d;if(d.includes(a.s))throw Error("Source object has a circular reference.");d.push(a.s);a.t!==a.s&&(a.d>c?Object.assign(a.t,a.s):(Object.keys(a.s).forEach(function(a){return function(b){var c=a.s[b];if(pa.call(a.t,b)){var d=a.t[b];if(na(c)&&na(d)){e.push({t:d,s:c,d:a.d+1});return}}a.t[b]=c}}(a)),a={s:a.s,t:a.t,d:a.d}))}};function D(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var E,ra="Webkit webkit Moz moz ms O o".split(" ");function sa(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function ta(a){return AMP.BaseElement.apply(this,arguments)||this}ga(ta,AMP.BaseElement);m=ta.prototype;m.getLayoutPriority=function(){return 1};m.isAlwaysFixed=function(){return!0};m.isLayoutSupported=function(){return!0};m.renderOutsideViewport=function(){return!0};m.L=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};function ua(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function va(a,b){var c,d=a.ownerDocument.defaultView,e=d!=F(d);if(e){if(G(d,b)){var f=J(d,b);if(f)return f}if(!c)return null}a=K(a);a=L(a);return G(a,b)?J(a,b):null}function wa(a,b){F(a);G(a,"bind");xa(a,a,"bind",function(){return b});J(a,"bind")}function M(a,b){a=F(a);return J(a,b)}function N(a,b){var c=K(a);c=L(c);return J(c,b)}function ya(a,b){return za(L(a),b)}function F(a){return a.__AMP_TOP||a}function K(a){return a.nodeType?M((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function L(a){a=K(a);return a.isSingleDoc()?a.win:a}function J(a,b){G(a,b);var c=O(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function xa(a,b,c,d){var e=O(a),f=e[c];f||(f=e[c]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});f.ctor||f.obj||(f.ctor=d,f.context=b,f.resolve&&J(a,c))}function Aa(a,b){var c=za(a,b);if(c)return c;a=O(a);a[b]=Ba();return a[b].promise}
function za(a,b){var c=O(a)[b];if(c){if(c.promise)return c.promise;J(a,b);return c.promise=Promise.resolve(c.obj)}return null}function O(a){var b=a.services;b||(b=a.services={});return b}function G(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)}function Ba(){var a=new ua,b=a,c=b.promise,d=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:d,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function Ca(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState}function Da(a,b){Ga(a,b)}function Ga(a,b){var c=Ca,d=c(a);if(d)b(a);else{var e=function(){c(a)&&(d||(d=!0,b(a)),a.removeEventListener("readystatechange",e))};a.addEventListener("readystatechange",e)}}function Ha(a){return new Promise(function(b){Ga(a,b)})};function Ia(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function Ja(a,b){Ia(a.documentElement,function(){return!!a.body},b)}function Ka(a,b){Da(a,function(){return Ja(a,b)})}function La(a){return new Promise(function(b){return Ka(a,b)})}
function Ma(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}function Na(a){return a.closest?a.closest("select"):Ma(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,"select"):!1})}function Oa(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)}function Pa(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};function Qa(a,b,c){var d=ya(a,b);if(d)return d;var e=K(a);return e.whenBodyAvailable().then(function(){return Ra(e.win,c,e.win.document.head)}).then(function(){var d=e.win;return d.ampExtendedElements&&d.ampExtendedElements[c]?Aa(L(a),b):null})}function Sa(a){var b=va(a,"bind");if(b)return Promise.resolve(b);b=a.ownerDocument.defaultView;var c=F(b);return b!==c?Ta(b):Qa(a,"bind","amp-bind")}
function Ra(a,b,c){if(c){var d=[];c=c.querySelectorAll("script[custom-element]");for(var e=0;e<c.length;e++)d.push(c[e].getAttribute("custom-element"))}else d=[];if(!d.includes(b))return Promise.resolve();var f=M(a,"extensions");return f.waitForExtension(a,b)}function Ta(a){return La(a.document).then(function(){return Ra(a,"amp-bind",a.document.head)}).then(function(){return a.ampExtendedElements&&a.ampExtendedElements["amp-bind"]?Aa(a,"bind"):null})};function P(){var a=100;this.ja=a;this.P=this.U=0;this.K=Object.create(null)}P.prototype.has=function(a){return!!this.K[a]};P.prototype.get=function(a){var b=this.K[a];if(b)return b.access=++this.P,b.payload};P.prototype.put=function(a,b){this.has(a)||this.U++;this.K[a]={payload:b,access:this.P};if(!(this.U<=this.ja)){w().warn("lru-cache","Trimming LRU cache");a=this.K;var c=this.P+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.U--)}};var Q=self.AMP_CONFIG||{},Ua={thirdParty:Q.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:Q.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof Q.thirdPartyFrameRegex?new RegExp(Q.thirdPartyFrameRegex):Q.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:Q.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof Q.cdnProxyRegex?new RegExp(Q.cdnProxyRegex):Q.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:Q.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:Q.localDev||!1};var Va=A({c:!0,v:!0,a:!0,ad:!0,action:!0}),Wa,Xa,Ya=/[?&]amp_js[^&]*/,Za=/[?&]amp_gsa[^&]*/,$a=/[?&]amp_r[^&]*/,ab=/[?&]amp_kit[^&]*/,bb=/[?&]usqp[^&]*/;
function R(a){var b;Wa||(Wa=self.document.createElement("a"),Xa=self.UrlCache||(self.UrlCache=new P));var c=b?null:Xa,d=Wa;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}
function cb(a,b){var c=void 0===c?"source":c;x(null!=a,"%s %s must be available",b,c);var d=a;a=d;"string"==typeof a&&(a=R(a));var e;(e="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,e=a.length-10,e=0<=e&&a.indexOf(".localhost",e)==e);x(e||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}function T(a){"string"==typeof a&&(a=R(a));return Ua.cdnProxyRegex.test(a.origin)}
function db(a){"string"==typeof a&&(a=R(a));if(!T(a))return a.href;var b=a.pathname.split("/");x(Va[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);x(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");var e;e=(e=a.search)&&"?"!=e?(e=e.replace(Ya,"").replace(Za,"").replace($a,"").replace(ab,"").replace(bb,"").replace(/^[?&]/,""))?"?"+e:"":"";return b+e+(a.hash||"")}
function eb(a,b){"string"==typeof b&&(b=R(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=R(d));c=c.replace(/\\/g,"/");var e=R(c);c=D(c.toLowerCase(),e.protocol)?e.href:D(c,"//")?d.protocol+c:D(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function fb(a){var b=R(a),c=ka(b.search);x(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};function gb(a,b){if("."==b)return a;var c=b.split(".");for(b=0;b<c.length;b++){var d=c[b];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function hb(a,b){try{return JSON.parse(a)}catch(c){b&&b(c)}}
function ib(a,b){var c=10;c=void 0===c?5:c;if(!isFinite(c)||0>c)throw Error("Invalid depth: "+c);if(a===b)return!0;for(a=[{a:a,b:b,depth:c}];0<a.length;){var d=a.shift();b=d.a;c=d.b;d=d.depth;if(0<d){if(typeof b!==typeof c)return!1;if(Array.isArray(b)&&Array.isArray(c)){if(b.length!==c.length)return!1;for(var e=0;e<b.length;e++)a.push({a:b[e],b:c[e],depth:d-1});continue}else if(b&&c&&"object"===typeof b&&"object"===typeof c){var f=Object.keys(b),g=Object.keys(c);if(f.length!==g.length)return!1;for(e=
0;e<f.length;e++){var h=f[e];a.push({a:b[h],b:c[h],depth:d-1})}continue}}if(b!==c)return!1}return!0};function jb(a,b,c,d,e){var f=void 0;f=void 0===f?".":f;c=void 0===c?0:c;d=void 0===d?!1:d;cb(b.getAttribute("src"),b);var g=M(a.win,"batched-xhr");return kb(b,c,d).then(function(a){e&&(a.fetchOpt.method="POST",a.fetchOpt.headers={"Content-Type":"application/x-www-form-urlencoded"},a.fetchOpt.body={ampViewerAuthToken:e});return g.fetchJson(a.xhrUrl,a.fetchOpt)}).then(function(a){return a.json()}).then(function(a){if(null==a)throw Error("Response is undefined.");return gb(a,f||".")})}
function kb(a,b,c){var d=a.getAttribute("src"),e=va(a,"url-replace");return(1<=b?e.expandUrlAsync(d):Promise.resolve(d)).then(function(d){if(1==b){var f=e.collectUnwhitelistedVarsSync(a);if(0<f.length)throw v().createError("URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. "+('Please add data-amp-replace="'+f.join(" ")+'" to the ')+("<"+a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var h={};a.hasAttribute("credentials")?h.credentials=a.getAttribute("credentials"):
h.requireAmpResponseSourceOrigin=!1;c&&(h.cache="reload");return{xhrUrl:d,fetchOpt:h}})};function ob(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?c.push(f):(d<e&&(a[d]=f),d++)}d<a.length&&(a.length=d)}function pb(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function qb(a){var b=a.getAttribute("cross-origin")||a.getAttribute("crossorigin");return b&&"amp-viewer-auth-token-via-post"===b.trim()?Qa(a,"amp-viewer-assistance","amp-viewer-assistance").then(function(a){x(a,'crossorigin="amp-viewer-auth-token-post" requires amp-viewer-assistance extension.');return a.getIdTokenPromise()}):Promise.resolve()};function rb(a){return AMP.BaseElement.apply(this,arguments)||this}ga(rb,AMP.BaseElement);m=rb.prototype;m.getLayoutPriority=function(){return 1};m.isAlwaysFixed=function(){return!0};m.isLayoutSupported=function(){return!0};
m.buildCallback=function(){var a=this;sa(this.element);this.element.setAttribute("aria-hidden","true");var b=this.element;b.hasAttribute("overridable")&&Sa(b).then(function(a){a.addOverridableKey(b.getAttribute("id"))});0<b.children.length&&sb(this);this.element.hasAttribute("src")&&tb(this,!0);this.registerAction("refresh",function(){x(a.element.hasAttribute("src"),'Can\'t refresh <amp-state> without "src" attribute.');tb(a,!1,!0)},100)};
m.mutatedAttributesCallback=function(a){if(N(this.element,"viewer").hasBeenVisible())void 0!==a.src&&tb(this,!1);else{var b=this.L();w().error(b,"Viewer must be visible before mutation.")}};m.renderOutsideViewport=function(){return!0};
function sb(a){var b=a.L(),c=a.element.children;if(1!=c.length)a.user().error(b,"Should contain exactly one <script> child.");else{var d=c[0];Pa(d)?(c=hb(d.textContent,function(c){a.user().error(b,"Failed to parse state. Is it valid JSON?",c)}),ub(a,c,!0)):a.user().error(b,'State should be in a <script> tag with type="application/json".')}}
function vb(a,b,c,d){var e=b.getAttribute("src"),f=1;if(c||R(db(e)).origin==R(db(a.win.location)).origin)f=2;return qb(b).then(function(c){return jb(a,b,f,d,c)})}function tb(a,b,c){var d=a.getAmpDoc();N(a.element,"viewer").whenFirstVisible().then(function(){return vb(d,a.element,b,c)}).then(function(c){return ub(a,c,b)})}function ub(a,b,c){if(void 0!==b&&null!==b){var d=x(a.element.id,"<amp-state> must have an id.");Sa(a.element).then(function(a){var e=z();e[d]=b;a.setState(e,c,!c)})}}
m.L=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};var wb=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function xb(a){for(var b=[],c;c=wb.exec(a);){var d=c[1],e=void 0,f=void 0;if(c[2]){var g=c[3].toLowerCase();if("w"==g)e=parseInt(c[2],10);else if("x"==g)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new yb(b)}
function yb(a){x(0<a.length,"Srcset must have at least one source");this.I=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}x(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?zb:Ab);this.ga=b}
yb.prototype.select=function(a,b){if(this.ga){b*=a;a=this.I;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var g=a[f].width,h=Math.abs(g-b);if(h<=1.1*d||1.2<b/e)c=f,d=h,e=g;else break}}else for(a=this.I,c=0,d=Infinity,e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c;return this.I[b].url};yb.prototype.getUrls=function(){return this.I.map(function(a){return a.url})};
yb.prototype.stringify=function(a){for(var b=[],c=this.I,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.ga?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function zb(a,b){x(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function Ab(a,b){x(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var Bb={"class":{blacklistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},Cb={width:null,height:null},Db={"AMP-AUTOCOMPLETE":{src:{allowedProtocols:{https:!0}}},"AMP-BASE-CAROUSEL":{"advance-count":null,"auto-advance-count":null,"auto-advance-interval":null,"auto-advance-loops":null,"auto-advance":null,horizontal:null,"initial-index":null,loop:null,"mixed-length":null,"side-slide-count":null,slide:null,"snap-align":null,"snap-by":null,snap:null,"visible-count":null},"AMP-BRIGHTCOVE":{"data-account":null,
"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-DATE-PICKER":{max:null,min:null,src:{allowedProtocols:{https:!0}}},"AMP-GOOGLE-DOCUMENT-EMBED":{src:null,title:null},"AMP-IFRAME":{src:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,https:!0}},srcset:{alternativeName:"src"}},"AMP-LIGHTBOX":{open:null},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null,"is-layout-container":null},
"AMP-SELECTOR":{disabled:null,selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-TIMEAGO":{datetime:null,title:null},"AMP-VIDEO":{alt:null,attribution:null,controls:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}}},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,http:!0,https:!0,mailto:!0,"fb-messenger":!0,intent:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,
value:null},DETAILS:{open:null},FIELDSET:{disabled:null},IMAGE:{"xlink:href":{allowedProtocols:{http:!0,https:!0}}},INPUT:{accept:null,accesskey:null,autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{blacklistedValueRegex:"(^|\\s)(button|image|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,
label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SELECT:{autofocus:null,disabled:null,multiple:null,required:null,size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,pattern:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,spellcheck:null,
wrap:null}},Eb={src:!0,srcset:!0,href:!0,"xlink:href":!0};function Fb(a){this.ia=a}Fb.prototype.canBind=function(a,b){return void 0!==Gb(this,a,b)};
Fb.prototype.isResultValid=function(a,b,c){var d=Gb(this,a,b);d&&d.alternativeName&&(d=Gb(this,a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&B(Eb,b)){if("srcset"===b){try{var e=xb(c)}catch(n){return v().error("amp-bind","Failed to parse srcset: ",n),!1}var f=e.getUrls()}else f=[c];for(a=0;a<f.length;a++){a:{b=f[a];var g=d;if(b){if(/__amp_source_origin/.test(b)){b=!1;break a}if(g=g.allowedProtocols)if(b=/^([^:\/?#.]+):[\s\S]*$/.exec(b),null!==b&&!pa.call(g,b[1].toLowerCase().trim())){b=
!1;break a}}b=!0}if(!b)return!1}}var h=d.blacklistedValueRegex;if(c&&h){var l=new RegExp(h,"i");if(l.test(c))return!1}return!0};function Gb(a,b,c){if(D(c,"aria-"))return null;if(!B(Eb,c)||a.ia){var d=B(Bb,c);if(void 0!==d)return d;var e=B(Cb,c);if(D(b,"AMP-")&&void 0!==e)return e;var f=B(Db,b);if(f)return f[c]}};var Hb=!1;function Ib(a){if(!Hb){Hb=!0;a=a.body;var b={opacity:1,visibility:"visible",animation:"none"},c;for(c in b){var d=a,e=b[c];var f=d.style;var g=c;if(D(g,"--"))f=g;else{E||(E=z());var h=E[g];if(!h){h=g;if(void 0===f[g]){var l=g.charAt(0).toUpperCase()+g.slice(1);b:{for(var n=0;n<ra.length;n++){var k=ra[n]+l;if(void 0!==f[k]){l=k;break b}}l=""}void 0!==f[l]&&(h=l)}E[g]=h}f=h}f&&(d.style[f]=e)}}};function U(){this.w=[]}U.prototype.peek=function(){var a=this.w.length;return a?this.w[a-1].item:null};U.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=b,d=-1,e=0,f=this.w.length;e<=f;){d=Math.floor((e+f)/2);if(d===this.w.length)break;if(this.w[d].priority<c)e=d+1;else if(0<d&&this.w[d-1].priority>=c)f=d-1;else break}this.w.splice(d,0,{item:a,priority:b})};U.prototype.forEach=function(a){for(var b=this.w.length;b--;)a(this.w[b].item)};
U.prototype.dequeue=function(){return this.w.length?this.w.pop().item:null};ha.Object.defineProperties(U.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.w.length}}});var Jb=/nochunking=1/.test(self.location.hash),Kb=Promise.resolve();function Lb(a,b){if(Jb)Kb.then(b);else{var c=Mb,d=K(a),e=L(d);xa(e,d,"chunk",c);N(a,"chunk").run(b,10)}}function V(a){this.state="not_run";this.S=a}function Nb(a,b){if("run"!=a.state){a.state="run";try{a.S(b)}catch(c){throw a.$(),c;}}}V.prototype.L=function(){return this.S.displayName||this.S.name};V.prototype.$=function(){};V.prototype.Z=function(){return!1};V.prototype.ea=function(){return!0};
function W(a,b,c){V.call(this,a);var d=this;this.h=b;this.j=null;c.then(function(a){d.j=a;d.j.isVisible()&&Nb(d,null);d.j.onVisibilityChanged(function(){d.j.isVisible()&&Nb(d,null)})})}ga(W,V);W.prototype.$=function(){Ib(self.document)};W.prototype.Z=function(){return this.j?this.j.isVisible():this.h.document.hidden?!1:!/visibilityState=(hidden|prerender)/.test(this.h.location.hash)};W.prototype.ea=function(){return!!this.j};
function Mb(a){var b=this;this.h=a.win;this.J=new U;this.W=this.X.bind(this);this.sa=Aa(L(a),"viewer");this.h.addEventListener("message",function(a){"amp-macro-task"==a.data&&b.X(null)})}Mb.prototype.run=function(a,b){var c=new V(a);Ob(this,c,b)};Mb.prototype.runForStartup=function(a){a=new W(a,this.h,this.sa);Ob(this,a,Number.POSITIVE_INFINITY)};function Ob(a,b,c){a.J.enqueue(b,c);Kb.then(function(){Pb(a)})}
function Qb(a,b){for(var c=a.J.peek();c&&"not_run"!==c.state;)a.J.dequeue(),c=a.J.peek();c&&b&&a.J.dequeue();return c}Mb.prototype.X=function(a){var b=this,c=Qb(this,!0);if(!c)return!1;Nb(c,a);Kb.then(function(){Pb(b)});return!0};function Rb(a){Kb.then(function(){a.W(null)})}function Pb(a){var b=Qb(a);b&&(b.Z()?Rb(a):b.ea()&&a.h.requestIdleCallback?Sb(a.h,a.W):a.h.postMessage("amp-macro-task","*"))}
function Sb(a,b){var c=15;function d(f){if(f.timeRemaining()<c){var g=2E3-(Date.now()-e);0>=g||f.didTimeout?b(f):a.requestIdleCallback(d,{timeout:g})}else b(f)}var e=Date.now();a.requestIdleCallback(d,{timeout:2E3})};function Tb(){this.F=z();this.o=null}m=Tb.prototype;m.get=function(a){return this.F[a]||null};m.whenSignal=function(a){var b=this.o&&this.o[a];if(!b){var c=this.F[a];null!=c?b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)}:(c=new ua,b={promise:c.promise,resolve:c.resolve,reject:c.reject});this.o||(this.o=z());this.o[a]=b}return b.promise};
m.signal=function(a,b){if(null==this.F[a]){var c=b||Date.now();this.F[a]=c;(a=this.o&&this.o[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};m.rejectSignal=function(a,b){null==this.F[a]&&(this.F[a]=b,(a=this.o&&this.o[a])&&a.reject&&(a.reject(b),a.resolve=void 0,a.reject=void 0))};m.reset=function(a){this.F[a]&&delete this.F[a];var b=this.o&&this.o[a];b&&!b.resolve&&delete this.o[a]};function Ub(a,b){function c(){d=0;var g=5E3-(a.Date.now()-e);if(0<g)d=a.setTimeout(c,g);else{var h=f;f=null;b.apply(null,h)}}var d=0,e=0,f=null;return function(b){for(var g=[],l=0;l<arguments.length;++l)g[l-0]=arguments[l];e=a.Date.now();f=g;d||(d=a.setTimeout(c,5E3))}};function Vb(a,b,c){var d="ww";b?(b=a.protocol+"//"+a.host,"about:"==a.protocol&&(b=""),a=b+"/dist"):a=Ua.cdn;return c?(b=q().singlePassType?q().singlePassType+"/":"",a+"/rtv/"+q().rtvVersion+"/"+b+d+".js"):a+"/"+d+".js"};function Wb(a){var b=this;this.h=a;this.ta=M(a,"xhr");var c=a.location,d=!1,e=!d,f=Vb(c,d,e);this.V=null;this.Y=this.ta.fetchText(f,{ampCors:!1}).then(function(a){return a.text()}).then(function(c){c=new a.Blob([c+"\n//# sourceurl="+f],{type:"text/javascript"});var d=a.URL.createObjectURL(c);b.V=new a.Worker(d);b.V.onmessage=b.qa.bind(b)});this.N={};this.ka=0;this.ha=[a]}
function Xb(a,b,c,d){return a.Y.then(function(){return new Promise(function(e,f){var g=a.ka++;a.N[g]={method:b,resolve:e,reject:f};e=d||a.h;f=a.ha.indexOf(e);var h=0<=f?f:a.ha.push(e)-1;a.V.postMessage({method:b,args:c,scope:h,id:g})})})}Wb.prototype.qa=function(a){var b=a.data;a=b.method;var c=b.returnValue;b=b.id;var d=this.N[b];d?(d.resolve(c),delete this.N[b]):w().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};
Wb.prototype.hasPendingMessages=function(){return 0<Object.keys(this.N).length};Wb.prototype.ua=function(){return this.Y};function Yb(){var a=Zb();return function(b){return setTimeout(b,a())}}function Zb(){var a=0;return function(){var b=Math.pow(1.5,a++);var c=b*(c||.3)*Math.random();.5<Math.random()&&(c*=-1);b+=c;return 1E3*b}};var X=self.AMPErrors||[];self.AMPErrors=X;function $b(a){$b=Yb();return $b(a)}function ac(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var bc;
function Y(a,b){try{if(a)if(void 0!==a.message)a=oa(a);else{var c=a;a=Error(ac(c));a.origError=c}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var d=b||a.associatedElement;d&&d.classList&&(d.classList.add("i-amphtml-error"),q().development&&(d.classList.add("i-amphtml-element-error"),d.setAttribute("error-message",a.message)));if(self.console){var e=console.error||console.log;a.messageArray?e.apply(console,a.messageArray):d?e.call(console,a.message,d):e.call(console,a.message)}d&&d.na&&
d.na("amp:error",a.message);cc.call(void 0,void 0,void 0,void 0,void 0,a)}}catch(f){setTimeout(function(){throw f;})}}function cc(a,b,c,d,e){var f=this;this&&this.document&&Ib(this.document);if(!q().development){var g=!1;try{g=dc()}catch(l){}if(!(g&&.01<Math.random())){var h=ec(a,b,c,d,e,g);h&&$b(function(){return fc(f,h)})}}}function fc(a,b){return gc(a,b).then(function(a){if(!a){var c=new XMLHttpRequest;c.open("POST",Ua.errorReporting,!0);c.send(JSON.stringify(b))}})}
function gc(a,b){var c=M(a,"ampdoc");if(!c.isSingleDoc())return Promise.resolve(!1);a=c.getAmpDoc();if(!a.getRootNode().documentElement.hasAttribute("report-errors-to-viewer"))return Promise.resolve(!1);var d=N(a,"viewer");return d.hasCapability("errorReporter")?d.isTrustedViewer().then(function(a){if(!a)return!1;d.sendMessage("error",A({m:b.m,a:b.a,s:b.s,el:b.el,v:b.v,jse:b.jse}));return!0}):Promise.resolve(!1)}
function ec(a,b,c,d,e,f){var g=a;e&&(g=e.message?e.message:String(e));g||(g="Unknown error");a=g;var h=!(!e||!e.expected);if(!/_reported_/.test(a)&&"CANCELLED"!=a){var l=!(self&&self.window),n=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a||l)if(h=!0,.001<n)return;var k=0<=a.indexOf("\u200b\u200b\u200b");if(!(k&&.1<n)){g=Object.create(null);g.v=q().rtvVersion;g.noAmp=f?"1":"0";g.m=a.replace("\u200b\u200b\u200b","");g.a=k?"1":"0";g.ex=h?"1":"0";g.dw=l?"1":"0";var t="1p";self.context&&
self.context.location?(g["3p"]="1",t="3p"):q().runtime&&(t=q().runtime);q().singlePassType&&(g.spt=q().singlePassType);g.rt=t;"inabox"===t&&(g.adid=q().a4aId);f=self;g.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;g.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(g.or=self.location.ancestorOrigins[0]);self.viewerState&&(g.vs=self.viewerState);self.parent&&self.parent!=self&&(g.iem="1");if(self.AMP&&self.AMP.viewer){var p=
self.AMP.viewer.getResolvedViewerUrl(),H=self.AMP.viewer.maybeGetMessagingOrigin();p&&(g.rvu=p);H&&(g.mso=H)}bc||(bc=hc());g.jse=bc;var S=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var C in f)S.push(C+"="+(f[C]?"1":"0"));g.exps=S.join(",");e?(g.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(g.args=JSON.stringify(e.args)),k||e.ignoreStack||!e.stack||(g.s=e.stack),e.message&&(e.message+=" _reported_")):(g.f=b||"",g.l=c||"",g.c=d||"");g.r=self.document.referrer;g.ae=X.join(",");g.fr=
self.location.originalHash||self.location.hash;b=a;25<=X.length&&X.splice(0,X.length-25+1);X.push(b);return g}}}function dc(){for(var a=self.document.querySelectorAll("script[src]"),b=0;b<a.length;b++)if(!T(a[b].src.toLowerCase()))return!0;return!1}
function hc(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(d){b=d.stack;if(D(b,"t@"))return"Safari";if(-1<b.indexOf(".prototype.t@"))return"Firefox";var c=b.split("\n").pop();if(/\bat .* \(/i.test(c))return"IE";if(D(b,"Error: message"))return"Chrome"}return"unknown"};function ic(a,b,c){var d=self.location;fb(c);var e=T(d),f=R(db(d));if("href"==b&&!D(c,"#"))return eb(c,f);if("src"==b)return"amp-img"==a?jc(c,f,e):eb(c,f);if("srcset"==b){try{var g=xb(c)}catch(h){return v().error("URL-REWRITE","Failed to parse srcset: ",h),c}return g.stringify(function(a){return jc(a,f,e)})}return c}
function jc(a,b,c){a=R(eb(a,b));return"data:"==a.protocol||T(a)||!c?a.href:Ua.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var kc=/^(i?-)?amp(html)?-/,lc=z({"AMP-CAROUSEL":["slide"],"AMP-LIST":["state","is-layout-container"],"AMP-SELECTOR":["selected"]});
function mc(a,b){var c=this;this.ampdoc=a;this.h=a.win;this.H=b||a.win;this.R=[];this.oa=Ub(this.h,function(){c.R.length=0});this.C=[];this.D=z();this.T=N(a,"history");this.aa=[];this.G=1E3;this.ba=N(a,"resources");this.B=z();this.ra=M(this.h,"timer");this.fa=null;this.j=N(this.ampdoc,"viewer");this.j.onMessageRespond("premutate",this.pa.bind(this));this.M=this.j.whenFirstVisible().then(function(){if(b){var c=b.document;return Ha(c).then(function(){return c})}return a.whenReady().then(function(){return a.getRootNode()})}).then(function(a){return nc(c,
a)});this.O=null;this.da=new Tb;var d=self.AMP;d.printState=d.printState||this.ma.bind(this);d.setState=d.setState||function(a){return c.setState(a)};d.eval=d.eval||this.la.bind(this)}mc.installInEmbedWindow=function(a,b){wa(a,new mc(b,a))};m=mc.prototype;m.signals=function(){return this.da};
m.setState=function(a,b,c){var d=this;try{qa(this.B,a)}catch(e){v().error("amp-bind","Failed to merge result from AMP.setState().",e)}w().info("amp-bind","state:",this.B);return b?Promise.resolve():this.O=this.M.then(function(){return oc(d)}).then(function(a){return pc(d,a,c)})};
m.invoke=function(a){var b=a,c=b.args,d=b.event,e=b.method,f=b.sequenceId,g=b.tagOrTarget;if(this.R.includes(f))return v().error("amp-bind","One state action allowed per event."),Promise.resolve();this.R.push(f);this.oa();if(b=c.__AMP_OBJECT_STRING__)switch(this.G=Math.min(2E3,Math.max(1E3,this.G+500)),this.da.signal("FIRST_MUTATE"),c={},d&&d.detail&&(c.event=d.detail),e){case "setState":return this.setStateWithExpression(b,c);case "pushState":return this.pushStateWithExpression(b,c);default:return Promise.reject(w().createError("Unrecognized method: %s.%s",
g,e))}else v().error("AMP-BIND","Please use the object-literal syntax, e.g. \"AMP.setState({foo: 'bar'})\" instead of \"AMP.setState(foo='bar')\".");return Promise.resolve()};m.setStateWithExpression=function(a,b){var c=this;w().info("amp-bind","setState:",'"'+a+'"');return this.O=qc(this,a,b).then(function(a){return c.setState(a)}).then(function(){return rc(c)}).then(function(a){a&&c.T.replace(a)})};
m.pushStateWithExpression=function(a,b){var c=this;w().info("amp-bind","pushState:",a);return qc(this,a,b).then(function(a){function b(){return c.setState(d)}var d=z();Object.keys(a).forEach(function(a){a:{var b=c.B[a];if(void 0!==b)try{var e=JSON.parse(JSON.stringify(b));break a}catch(n){w().error("amp-bind","Failed to copy JSON ("+b+") with error: "+n)}e=null}d[a]=e});return c.setState(a).then(function(){return rc(c)}).then(function(a){c.T.push(b,a)})})};
function rc(a){var b=A({data:A({"amp-bind":a.B}),title:a.H.document.title});return a.j.isEmbedded()?a.j.isTrustedViewer().then(function(a){return a?b:null}):Promise.resolve(b)}
m.scanAndApply=function(a,b,c){function d(a){sc(e,b).then(function(b){w().info("amp-bind","\u2937","\u0394:",a-b,", \u2211:",e.numberOfBindings())});return Promise.resolve()}var e=this;c=void 0===c?2E3:c;w().info("amp-bind","rescan:",a,b);if(this.numberOfBindings()>this.G)return tc(this),d(0);var f=[],g=a.slice();a.forEach(function(a){Array.prototype.push.apply(g,a.querySelectorAll("[i-amphtml-binding]"))});g.forEach(function(a){uc(e,a,Number.POSITIVE_INFINITY,f)});var h=f.length;if(0===h)return d(0);
var l=vc(this,f).then(function(){return oc(e).then(function(b){return wc(e,b,a)})}).then(function(){d(h)});return this.ra.timeoutPromise(c,l,"Timed out waiting for amp-bind to process rendered template.")};m.getStateValue=function(a){a=gb(this.B,a);return na(a)||Array.isArray(a)?JSON.stringify(a):String(a)};
function nc(a,b){var c=!xc(a);a.fa=new Fb(c);return Z(a,"bind.init",[c]).then(function(){return Promise.all([yc(a),zc(a,[b])])}).then(function(c){w().info("amp-bind","\u2937","\u0394:",c);b.addEventListener("amp:dom-update",function(b){return Ac(a,b)});if(q().development)return oc(a).then(function(b){return Bc(a,b)})}).then(function(){return Cc(a,b)})}
function Cc(a,b){var c=b.querySelectorAll("AMP-STATE");if(0<c.length){var d=r(c).map(function(a){return a.whenBuilt()});Promise.all(d).then(function(){a.j.sendMessage("bindReady",void 0)})}else a.j.sendMessage("bindReady",void 0)}function xc(a){var b=a.H.document.documentElement,c=b.hasAttribute("amp4email")||b.hasAttribute("\u26a14email");return c}m.numberOfBindings=function(){return this.C.reduce(function(a,b){return a+b.boundProperties.length},0)};m.xa=function(a){this.G=a};m.va=function(){return this.T};
m.pa=function(a){var b=this,c=[];return this.M.then(function(){Object.keys(a.state).forEach(function(d){b.aa.includes(d)||(delete a.state[d],c.push(d))});0<c.length&&v().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+c.join(", "));return b.setState(a.state)})};m.addOverridableKey=function(a){this.aa.push(a)};
function yc(a){var b=a.ampdoc.getBody().querySelectorAll("AMP-BIND-MACRO"),c=[];Oa(b,function(a){var b=(a.getAttribute("arguments")||"").split(",").map(function(a){return a.trim()});c.push({id:a.getAttribute("id"),argumentNames:b,expressionString:a.getAttribute("expression")})});return 0==c.length?Promise.resolve(0):Z(a,"bind.addMacros",[c]).then(function(a){a.forEach(function(a,c){Dc(a,"amp-bind: Parsing amp-bind-macro failed.",b[c])});return c.length})}
function zc(a,b){var c=b.map(function(b){var c=a.G-a.numberOfBindings();return Ec(a,b,c).then(function(b){var c=b.bindings,d=b.limitExceeded;d&&tc(a);return c})});return Promise.all(c).then(function(b){b=Array.prototype.concat.apply([],b);return 0<b.length?vc(a,b):0})}function tc(a){w().expectedError("amp-bind","Maximum number of bindings reached (%s). Additional elements with bindings will be ignored.",a.G)}
function vc(a,b){return Z(a,"bind.addBindings",[b]).then(function(c){Object.keys(c).forEach(function(b){var d=a.D[b];0<d.length&&Dc(c[b],'amp-bind: Expression compile error in "'+b+'".',d[0])});return b.length})}
function sc(a,b){ob(a.C,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a.element))return!0;return!1});var c=[],d;for(d in a.D){var e=a.D[d];ob(e,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a))return!0;return!1});0==e.length&&(c.push(d),delete a.D[d])}var f=c.length;return 0<f?Z(a,"bind.removeBindingsWithExpressionStrings",[c]).then(function(){return f}):Promise.resolve(0)}
function Ec(a,b,c){function d(){var b=f.currentNode;if(!b)return!0;if(b.nodeType!==Node.ELEMENT_NODE)return!f.nextNode();var d=c-e.length;uc(a,b,d,e)&&(g=!0);return!f.nextNode()||g}var e=[],f=(b.nodeType==Node.DOCUMENT_NODE?b:b.ownerDocument).createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1),g=!1;return new Promise(function(b){function c(f){var k=!1;if(f&&!f.didTimeout)for(;1<f.timeRemaining()&&!k;)k=d();else{var h=250;for(f=0;f<h&&!k;f++)k=d()}k?b({bindings:e,limitExceeded:g}):Lb(a.ampdoc,c)}Lb(a.ampdoc,
c)})}function uc(a,b,c,d){var e=!1,f=Fc(a,b);f.length>c&&(f.length=c,e=!0);0<f.length&&a.C.push({element:b,boundProperties:f});var g=b.tagName;f.forEach(function(c){var e=c,f=e.expressionString;d.push({tagName:g,property:e.property,expressionString:f});a.D[f]||(a.D[f]=[]);a.D[f].push(b)});return e}
function Fc(a,b){for(var c=[],d=b.attributes,e=0,f=d.length;e<f;e++){a:{var g=void 0,h=a,l=d[e];var n=b;var k=n.tagName,t=l.name;if(2<t.length&&"["===t[0]&&"]"===t[t.length-1])g=t.substr(1,t.length-2);else if(D(t,"data-amp-bind-")&&(g=t.substr(14),n.hasAttribute("["+g+"]"))){n=null;break a}if(g){if(h.fa.canBind(k,g)){n={property:g,expressionString:l.value};break a}g=v().createError("%s: Binding to [%s] on <%s> is not allowed.","amp-bind",g,k);Y(g,n)}n=null}n&&c.push(n)}return c}
function qc(a,b,c){return a.M.then(function(){Object.assign(c,a.B);return Z(a,"bind.evaluateExpression",[b,c])}).then(function(a){var b=a.result;if(a=a.error)throw Dc(a,"amp-bind: Expression eval failed.");w().info("amp-bind","\u2937",b);return b})}
function oc(a){var b=Z(a,"bind.evaluateBindings",[a.B]);return b.then(function(b){var c=b.results,e=b.errors;Object.keys(e).forEach(function(b){var c=a.D[b];if(0<c.length){var d=e[b],f=v().createError('%s: Expression evaluation error in "%s". %s',"amp-bind",b,d.message);f.stack=d.stack;Y(f,c[0])}});w().info("amp-bind","bindings:",c);return c})}
function Bc(a,b){var c=void 0===c?null:c;var d=void 0===d?!0:d;var e={};a.C.forEach(function(a){var f=a.element;a=a.boundProperties;c&&!Gc(c,f)||a.forEach(function(a){var c=b[a.expressionString];if(void 0!==c){var g=a.property,k=lc[f.tagName];if(k&&k.includes(g))c=null;else{switch(g){case "text":g=f.textContent;c=String(c);k=g.trim()===c.trim();break;case "class":g=[];for(k=0;k<f.classList.length;k++){var h=f.classList[k];kc.test(h)||g.push(h)}h=[];Array.isArray(c)?h=c:"string"===typeof c?(k=c.trim(),
0<k.length&&(h=k.split(" "))):(k=v().createError('%s: "%s" is not a valid result for [class].',"amp-bind",c),Y(k,f));b:{k=g;var p=h;if(k.length!==p.length)k=!1;else{h=(Array.isArray(k)?k:r(k)).sort();p=(Array.isArray(p)?p:r(p)).sort();for(var H=0;H<k.length;H++)if(h[H]!==p[H]){k=!1;break b}k=!0}}break;default:g=f.getAttribute(g),k=!0===c?""===g:!1===c?null===g:"number"===typeof c?Number(g)===c:g===c}c=k?null:{expected:c,actual:g}}var S=c;if(S){c=f.tagName;g=a.property;a=a.expressionString;k=S;h=k.expected;
var C=k.actual;e[c+"["+g+"]"+h+":"+C]=!0;d&&v().warn("amp-bind","Default value ("+C+") does not match first "+("result ("+h+") for <"+c+" ["+g+']="')+(a+'">. We recommend writing expressions with ')+"matching default values, but this can be safely ignored if intentional.")}}})});return Object.keys(e)}function Gc(a,b){for(var c=0;c<a.length;c++)if(a[c].contains(b))return!0;return!1}
function Hc(a,b){var c=[];a.forEach(function(a){var d=a.previousResult,f=b[a.expressionString];void 0===f||ib(f,d)||(a.previousResult=f,c.push({boundProperty:a,newValue:f}))});return c}function pc(a,b,c){var d=a.C.map(function(d){return c&&"AMP-STATE"===d.element.tagName?Promise.resolve():Ic(a,b,d)});return Promise.all(d).then(function(){w().info("amp-bind","updated:",d.length,"elements")})}
function wc(a,b,c){var d=[];a.C.forEach(function(e){c.forEach(function(c){c.contains(e.element)&&d.push(Ic(a,b,e))})});return Promise.all(d).then(function(){w().info("amp-bind","updated:",d.length,"elements")})}
function Ic(a,b,c){var d=c.element,e=Hc(c.boundProperties,b);return 0===e.length?Promise.resolve():a.ba.mutateElement(d,function(){var b=z(),c,h;e.forEach(function(e){var f=e,g=f.boundProperty;f=f.newValue;a:{var p=g.property;var l=d.tagName;switch(p){case "text":p=!0;var n=String(f);"TEXTAREA"===l&&(d.value=n,p=!1);"TITLE"===l&&d.parentNode===a.H.document.head&&(a.H.document.title=n);p&&(d.textContent=n);break;case "class":p=[];for(l=0;l<d.classList.length;l++)n=d.classList[l],kc.test(n)&&p.push(n);
Array.isArray(f)||"string"===typeof f?d.setAttribute("class",p.concat(f).join(" ")):null===f?d.setAttribute("class",p.join(" ")):(p=v().createError('%s: "%s" is not a valid result for [class].',"amp-bind",f),Y(p,d));break;default:var C="INPUT"===l&&p in d,I=d.getAttribute(p);l=!1;if("boolean"===typeof f){if(C&&d[p]!==f&&(d[p]=f,l=!0),f&&""!==I?(d.setAttribute(p,""),l=!0):f||null===I||(d.removeAttribute(p),l=!0),l&&"OPTION"===d.tagName&&"selected"===p&&f&&M(a.h,"platform").isSafari()&&(n=Na(d))){var y=
r(n.options).indexOf(d);0<=y&&(n.selectedIndex=y)}}else if(f!==I)b:{I=String(f);try{n=d.tagName.toLowerCase();y=p.toLowerCase();var Ea="src"==y||"href"==y||"srcset"==y?ic(n,y,I):I;if(T(self.location)&&"a"===n&&"href"===y){var lb=d.getAttribute(y),mb="#"===Ea[0],nb=lb&&"#"===lb[0];mb&&!nb?(d.__AMP_ORIGINAL_TARGET_VALUE_||(d.__AMP_ORIGINAL_TARGET_VALUE_=d.getAttribute("target")),d.removeAttribute("target")):nb&&!mb&&d.setAttribute("target",d.__AMP_ORIGINAL_TARGET_VALUE_||"_top")}C&&(d[y]=Ea);d.setAttribute(y,
Ea);l=!0;break b}catch(Jc){l=v().createError('%s: "%s" is not a valid result for [%]',"amp-bind",I,p,Jc),Y(l,d)}l=!1}if(l){p={name:p,value:f};break a}}p=null}var Fa=p;Fa&&(b[Fa.name]=Fa.value,g=g.property,"width"==g?c="number"===typeof f&&isFinite(f)?Number(f):c:"height"==g&&(h="number"===typeof f&&isFinite(f)?Number(f):h))});void 0===c&&void 0===h||a.ba.changeSize(d,h,c);if("function"===typeof d.mutatedAttributesCallback)try{d.mutatedAttributesCallback(b)}catch(n){var l=v().createError("%s: Applying expression results (%s) failed with error,",
"amp-bind",JSON.stringify(b),n);Y(l,d)}})}function Ac(a,b){b=b.target;var c=b.parentNode;c&&"AMP-LIST"==c.tagName||(w().info("amp-bind","dom_update:",b),Kc(a,[b],[b]).then(function(){}))}function Kc(a,b,c){var d=0;return sc(a,b).then(function(b){d=b;return zc(a,c)}).then(function(b){w().info("amp-bind","\u2937","\u0394:",b-d,", \u2211:",a.numberOfBindings());return{added:b,removed:d}})}
function Z(a,b,c){var d=a.h;a=a.H;if(d.Worker){var e=F(d);xa(e,e,"amp-worker",Wb);d=M(d,"amp-worker");b=Xb(d,b,c||[],a)}else b=Promise.reject("Worker not supported in window.");return b}function Dc(a,b,c){b=v().createError("%s %s",b,a.message);b.stack=a.stack;Y(b,c);return b}
m.ma=function(a){if(a)if("string"==typeof a){var b=gb(this.B,a);v().info("amp-bind",b)}else a.nodeType==Node.ELEMENT_NODE?(b=v().assertElement(a),Lc(this,b)):v().info("amp-bind",'Invalid argument. Pass a JSON expression or an element instead e.g. AMP.printState("foo.bar") or AMP.printState($0) after selecting an element.');else v().info("amp-bind",this.B)};
function Lc(a,b){var c=pb(a.C,function(a){return a.element==b});if(0>c)v().info("amp-bind","Element has no bindings:",b);else{var d=[],e=a.C[c].boundProperties;e.forEach(function(b){d.push(qc(a,b.expressionString,a.B))});Promise.all(d).then(function(a){var b=z();e.forEach(function(c,d){b[c.property]=a[d]});v().info("amp-bind",b)})}}m.la=function(a){qc(this,a,this.B).then(function(a){v().info("amp-bind",a)})};m.wa=function(){return this.M};m.ya=function(){return this.O};(function(a){a.registerServiceForDoc("bind",mc);a.registerElement("amp-state",rb);a.registerElement("amp-bind-macro",ta)})(self.AMP);
})});
//# sourceMappingURL=amp-bind-0.1.js.map

